import ast

# Set of forbidden builtin functions and names that pose security risks
BLOCKED_NAMES = {
    "eval",
    "exec",
    "compile",
    "__import__"
}

# Set of restricted modules to prevent unauthorized operations (e.g. system calls, networking)
BLOCKED_MODULES = {
    "subprocess",
    "socket",
    "requests"
}



def validate_generated_code(code: str) -> dict:
    """Validate python code generated by the agent. Checks for syntax errors and blocks unsafe imports/functions (subprocess, socket, requests, eval, exec, compile, __import__)."""

    try:
        # Parse the code into an Abstract Syntax Tree (AST) to verify python syntax
        tree = ast.parse(code)

    except SyntaxError as exc:
        return {
            "valid": False,
            "reason": f"Invalid Python syntax: {exc}"
        }

    # Traverse the AST to check for unauthorized imports and execution calls
    for node in ast.walk(tree):

        # Check standard import statements (e.g., import subprocess)
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]

                if root in BLOCKED_MODULES:
                    return {
                        "valid": False,
                        "reason": f"Blocked module: {root}"
                    }

        # Check relative/from import statements (e.g., from socket import ...)
        if isinstance(node, ast.ImportFrom):
            if node.module:
                root = node.module.split(".")[0]

                if root in BLOCKED_MODULES:
                    return {
                        "valid": False,
                        "reason": f"Blocked module: {root}"
                    }

        # Check for blocked function execution calls (e.g., exec(...))
        if isinstance(node, ast.Call):

            if isinstance(node.func, ast.Name):

                if node.func.id in BLOCKED_NAMES:
                    return {
                        "valid": False,
                        "reason": (
                            f"Blocked function: "
                            f"{node.func.id}"
                        )
                    }

    return {
        "valid": True
    }